---

BASE_DIR: 'C:\Users\rhunt\test'
SRC_DIR:  '{{ BASE_DIR }}\SRC'
DEST_DIR: '{{ BASE_DIR }}\DEST' 
ARCHIVE_DIR: '{{ BASE_DIR }}\20.02.01'

NEW_DIR:  '{{ DEST_DIR }}\test'
NEW_FILE_1: '{{ NEW_DIR }}\test_1.dat'
NEW_FILE_2: '{{ NEW_DIR }}\test_2.dat'

...

